language: ruby
bundler_args: --jobs 4 --without integration
rvm:
  - 2.0.0
  - 2.1
cache: bundler
sudo: false  # travis docker container
env:
  matrix:
    - CHEF_VERSION=10.30
    - CHEF_VERSION=11.16
    - CHEF_VERSION=12.0
before_script:
  - "gem install bundler-audit --no-rdoc --no-ri && bundle-audit update"
script:
  - bundle-audit
  - bundle exec rake license_finder
  - bundle exec rake rubocop
  - bundle exec rake foodcritic
  - bundle exec rake chefspec
  - bundle exec rake kitchen:all
